### ISSUE TITLE
Location indicator not appearing initially.

### ISSUE THREAD

**Issue by eric-parent** [michael-han/DriveSafe#22]
Location indicator does not appear initially after creating new group. Indicator does appear after refreshing the page (for example, going to group settings and going back to the dashboard).

**Comment by lusilva** [comment]
This is because when the dashboard is first rendered, it checks if the user is in a group and if he/she is then it places the indicator on the map along with driver indicators for every driver in the group. We may be able to circumvent this by just adding the indicator on the map even when the user is not in the group.
